import BrandLogo from "../components/ui/BrandLogo";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import type { Variants } from "framer-motion";
import {
  Activity, ArrowRight, BrainCircuit, Check, ChevronRight, Database,
  FileCheck2, Fingerprint, LayoutDashboard, Lock, Menu, Network,
  ShieldCheck, Sparkles, Target, TrendingUp, Users, X,
} from "lucide-react";
import ThemeToggle from "../components/ui/ThemeToggle";

const flow = [
  ["01", "Upload", "Raw academic files enter a controlled workspace."],
  ["02", "Extract", "Agent 10 identifies structure and meaning."],
  ["03", "Validate", "People verify what the system found."],
  ["04", "Commit", "Approved records become operational data."],
  ["05", "Detect", "Signals surface before they become invisible."],
  ["06", "Intervene", "Teams move from evidence to action."],
  ["07", "Decide", "Leadership sees the shape of academic health."],
];

const reveal: Variants = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: "easeOut" } } };

function ProductPreview() {
  return (
    <div className="relative rounded-2xl border border-border bg-surface p-3 shadow-[0_28px_80px_hsl(var(--glass-shadow)/0.16)]">
      <div className="rounded-xl border border-border overflow-hidden bg-background">
        <div className="flex items-center justify-between border-b border-border px-4 py-3">
          <div className="flex items-center gap-2"><div className="h-2 w-2 rounded-full bg-indigo-600" /><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-secondary">Illustrative command center</span></div>
          <span className="text-[10px] font-medium text-secondary">Live product preview</span>
        </div>
        <div className="grid grid-cols-[48px_1fr] sm:grid-cols-[148px_1fr] min-h-[330px]">
          <div className="border-r border-border bg-surface px-2 py-4 sm:px-3">
            <div className="mb-5 px-2 text-[9px] font-bold uppercase tracking-[0.18em] text-secondary hidden sm:block">Workspace</div>
            {[LayoutDashboard, TrendingUp, Target, Users].map((Icon, i) => <div key={i} className={`mb-2 flex items-center gap-2 rounded-lg px-2 py-2 ${i === 0 ? "bg-indigo-50 text-indigo-800 dark:bg-indigo-500/10 dark:text-indigo-300" : "text-secondary"}`}><Icon size={15} /><span className="hidden sm:block text-xs font-semibold">{["Overview", "Trends", "Risk center", "Students"][i]}</span></div>)}
          </div>
          <div className="p-4 sm:p-6">
            <div className="flex items-start justify-between gap-4 mb-5"><div><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-indigo-700 dark:text-indigo-300">Academic command center</div><div className="mt-1 text-lg font-bold text-primary">A clear view of what needs attention</div></div><div className="hidden sm:flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-2.5 py-1.5 text-[10px] font-bold text-emerald-800 dark:border-emerald-500/20 dark:bg-emerald-500/10 dark:text-emerald-300"><ShieldCheck size={13} /> Verified scope</div></div>
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 mb-4">{["Pass rate", "Students", "Open flags", "Data trust"].map((label, i) => <div key={label} className={`rounded-lg border p-3 ${i === 2 ? "border-amber-200 bg-amber-50/70 dark:border-amber-500/20 dark:bg-amber-500/10" : "border-border bg-surface"}`}><div className="text-[9px] font-bold uppercase tracking-wider text-secondary">{label}</div><div className="mt-2 text-lg font-bold text-primary">{i === 0 ? "—" : i === 1 ? "—" : i === 2 ? "Review" : "Live"}</div><div className="mt-1 text-[9px] text-secondary">From connected data</div></div>)}</div>
            <div className="grid gap-3 sm:grid-cols-[1.35fr_0.65fr]"><div className="rounded-lg border border-border bg-surface p-3"><div className="flex justify-between text-[10px] font-bold text-primary"><span>Performance signal</span><span className="text-secondary">Current scope</span></div><div className="mt-5 flex h-28 items-end gap-1.5 border-b border-border px-1">{[28, 42, 35, 58, 50, 67, 61, 74, 68, 82, 77, 88].map((height, i) => <div key={i} className="flex-1 rounded-t-sm bg-indigo-700/70 transition-all hover:bg-indigo-600" style={{ height: `${height}%` }} />)}</div><div className="mt-2 flex justify-between text-[9px] text-secondary"><span>Earlier</span><span>Now</span></div></div><div className="rounded-lg border border-border bg-surface p-3"><div className="text-[10px] font-bold text-primary">Attention queue</div><div className="mt-3 space-y-2">{[["Review", "amber"], ["Verified", "green"], ["Action", "indigo"]].map(([label, tone]) => <div key={label} className="flex items-center justify-between border-b border-border pb-2 text-[10px]"><span className="text-secondary">{label}</span><span className={`h-2 w-2 rounded-full ${tone === "amber" ? "bg-amber-500" : tone === "green" ? "bg-emerald-500" : "bg-indigo-600"}`} /></div>)}</div></div></div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function Landing() {
  const navigate = useNavigate();
  const [scrolled, setScrolled] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 24);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMobileOpen(false); };

  return (
    <div className="min-h-screen bg-background text-primary selection:bg-indigo-500/20">
      <nav className={`fixed inset-x-0 top-0 z-50 border-b transition-all ${scrolled ? "border-border bg-background/90 py-3 backdrop-blur-xl" : "border-transparent bg-transparent py-5"}`}>
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 lg:px-8"><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="BodhSight home"><BrandLogo /></button><div className="hidden items-center gap-8 md:flex"><button onClick={() => scrollTo("platform")} className="text-sm font-semibold text-secondary hover:text-primary">Platform</button><button onClick={() => scrollTo("workflow")} className="text-sm font-semibold text-secondary hover:text-primary">Workflow</button><button onClick={() => scrollTo("governance")} className="text-sm font-semibold text-secondary hover:text-primary">Governance</button></div><div className="hidden items-center gap-3 md:flex"><ThemeToggle /><button onClick={() => navigate("/login")} className="px-3 py-2 text-sm font-semibold text-secondary hover:text-primary">Sign in</button><button onClick={() => navigate("/login")} className="inline-flex items-center gap-2 rounded-lg bg-indigo-800 px-4 py-2 text-sm font-bold text-white shadow-sm hover:bg-indigo-700">Enter platform <ArrowRight size={15} /></button></div><button onClick={() => setMobileOpen(true)} className="rounded-lg border border-border p-2 md:hidden" aria-label="Open navigation"><Menu size={20} /></button></div>
      </nav>
      <AnimatePresence>{mobileOpen && <motion.div initial={{ opacity: 0, x: "100%" }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: "100%" }} className="fixed inset-0 z-[60] bg-background p-6"><div className="flex items-center justify-between"><BrandLogo /><button onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X /></button></div><div className="mt-12 flex flex-col gap-6 text-lg font-semibold"><button onClick={() => scrollTo("platform")} className="text-left">Platform</button><button onClick={() => scrollTo("workflow")} className="text-left">Workflow</button><button onClick={() => scrollTo("governance")} className="text-left">Governance</button><ThemeToggle showLabel /><button onClick={() => navigate("/login")} className="mt-3 rounded-lg bg-indigo-800 py-3 text-white">Enter platform</button></div></motion.div>}</AnimatePresence>
      <main>
        <section className="relative overflow-hidden border-b border-border pt-28 pb-12 lg:pt-36 lg:pb-20"><div className="absolute inset-0 bg-[linear-gradient(to_right,hsl(var(--border)/0.32)_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border)/0.32)_1px,transparent_1px)] bg-[size:54px_54px] [mask-image:linear-gradient(to_bottom,black,transparent_82%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 md:grid-cols-[0.88fr_1.12fr] lg:gap-14 lg:px-8"><motion.div initial="hidden" animate="visible" variants={reveal}><div className="mb-5 inline-flex items-center gap-2 rounded-md border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.16em] text-indigo-800 dark:border-indigo-500/20 dark:bg-indigo-500/10 dark:text-indigo-300"><Sparkles size={13} /> Academic intelligence platform</div><h1 className="max-w-2xl text-4xl font-bold leading-[1.04] tracking-[-0.04em] text-primary sm:text-5xl lg:text-[4.6rem]">Turn academic data into <span className="text-indigo-700 dark:text-indigo-300">timely action.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-secondary lg:text-lg lg:leading-8">BodhSight transforms raw institutional data into verified insight, early intervention, and confident academic decisions.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={() => navigate("/login")} className="inline-flex items-center justify-center gap-2 rounded-lg bg-indigo-800 px-5 py-3.5 text-sm font-bold text-white shadow-[0_12px_30px_hsl(var(--accent)/0.2)] hover:bg-indigo-700">Enter BodhSight <ArrowRight size={16} /></button><button onClick={() => scrollTo("workflow")} className="inline-flex items-center justify-center gap-2 rounded-lg border border-border bg-surface px-5 py-3.5 text-sm font-bold text-primary hover:bg-surface-secondary">See how it works <ChevronRight size={16} /></button></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-secondary"><span className="inline-flex items-center gap-2"><Check size={14} className="text-indigo-700" /> Evidence-backed</span><span className="inline-flex items-center gap-2"><Check size={14} className="text-indigo-700" /> Role-aware</span><span className="inline-flex items-center gap-2"><Check size={14} className="text-indigo-700" /> PostgreSQL connected</span></div></motion.div><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15, duration: 0.65 }}><ProductPreview /></motion.div></div></section>
        <section id="platform" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[0.72fr_1.28fr]"><div><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-indigo-700 dark:text-indigo-300">A decision layer for academia</div><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">See the signal. Understand the why. Move with confidence.</h2><p className="mt-5 max-w-md leading-7 text-secondary">The platform connects ingestion, verification, analytics, and intervention into one accountable operating rhythm.</p></div><div className="grid gap-5 sm:grid-cols-3"><article className="border-t-2 border-indigo-700 pt-5"><div className="mb-7 flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-50 text-indigo-800 dark:bg-indigo-500/10 dark:text-indigo-300"><Activity size={19} /></div><h3 className="text-xl font-bold">Detect</h3><p className="mt-3 text-sm leading-6 text-secondary">Find academic risk before it disappears inside a spreadsheet or averages out of view.</p></article><article className="border-t-2 border-amber-500 pt-5"><div className="mb-7 flex h-10 w-10 items-center justify-center rounded-lg bg-amber-50 text-amber-800 dark:bg-amber-500/10 dark:text-amber-300"><BrainCircuit size={19} /></div><h3 className="text-xl font-bold">Intervene</h3><p className="mt-3 text-sm leading-6 text-secondary">Turn a performance signal into a focused review, recommendation, or student support action.</p></article><article className="border-t-2 border-slate-500 pt-5"><div className="mb-7 flex h-10 w-10 items-center justify-center rounded-lg bg-surface-secondary text-primary"><Network size={19} /></div><h3 className="text-xl font-bold">Decide</h3><p className="mt-3 text-sm leading-6 text-secondary">Give academic leaders a shared, defensible view of what is happening and what comes next.</p></article></div></div></section>
        <section id="workflow" className="border-y border-border bg-surface py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-indigo-700 dark:text-indigo-300">The operating rhythm</div><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">From raw data to academic action.</h2></div><p className="max-w-md text-sm leading-6 text-secondary">Every transition keeps the evidence visible, the human checkpoint explicit, and the next decision closer.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-xl border border-border bg-border md:grid-cols-4 lg:grid-cols-7">{flow.map(([number, title, desc], i) => <motion.div key={title} initial="hidden" whileInView="visible" viewport={{ once: true, margin: "-60px" }} variants={reveal} transition={{ delay: i * 0.04 }} className="group relative bg-background p-5 hover:bg-indigo-50/50 dark:hover:bg-indigo-500/5"><div className="flex items-center justify-between"><span className="font-mono text-xs font-bold text-indigo-700 dark:text-indigo-300">{number}</span>{i < flow.length - 1 && <ArrowRight size={13} className="text-border group-hover:text-indigo-700" />}</div><h3 className="mt-10 text-sm font-bold uppercase tracking-wider">{title}</h3><p className="mt-3 text-xs leading-5 text-secondary">{desc}</p></motion.div>)}</div></div></section>
        <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid items-center gap-14 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-xl border border-border bg-surface p-5 shadow-sm"><div className="flex items-center gap-3 border-b border-border pb-4"><div className="rounded-lg bg-indigo-50 p-2 text-indigo-800 dark:bg-indigo-500/10 dark:text-indigo-300"><FileCheck2 size={17} /></div><div><div className="text-sm font-bold">Evidence chain</div><div className="text-xs text-secondary">Conceptual product view</div></div></div><div className="space-y-3 pt-5">{[["Source record", "Captured from approved academic data"], ["System validation", "Rules and confidence made visible"], ["Human decision", "Review remains accountable"], ["Operational insight", "Only approved evidence informs action"]].map(([title, desc], i) => <div key={title} className="flex gap-3"><div className="flex flex-col items-center"><div className={`mt-1 h-2.5 w-2.5 rounded-full ${i === 3 ? "bg-indigo-700" : "border-2 border-indigo-700"}`} />{i < 3 && <div className="h-full w-px bg-border" />}</div><div className="pb-5"><div className="text-sm font-bold">{title}</div><div className="mt-1 text-xs text-secondary">{desc}</div></div></div>)}</div></div><div id="governance"><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-indigo-700 dark:text-indigo-300">Trust by design</div><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Intelligence that respects the institution.</h2><p className="mt-5 leading-7 text-secondary">BodhSight keeps role-based access, evidence lineage, and human review close to every operational decision.</p><div className="mt-7 space-y-4">{[[Lock, "RBAC at the boundary", "The backend remains the security boundary for every scope and action."], [Fingerprint, "Evidence stays visible", "Signals can be traced back to the data and validation stage that produced them."], [ShieldCheck, "Calm by default", "The interface reserves urgency for the moments that actually need it."]].map(([Icon, title, desc]) => <div key={title as string} className="flex gap-3"><Icon size={18} className="mt-1 shrink-0 text-indigo-700 dark:text-indigo-300" /><div><div className="text-sm font-bold">{title as string}</div><div className="mt-1 text-sm leading-6 text-secondary">{desc as string}</div></div></div>)}</div></div></div></section>
        <section className="border-t border-border bg-surface px-5 py-24 lg:px-8"><div className="mx-auto max-w-4xl text-center"><div className="mx-auto mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-800 text-white"><Database size={22} /></div><h2 className="text-4xl font-bold tracking-tight sm:text-5xl">BodhSight turns academic complexity into clarity.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-secondary">Bring data, validation, intelligence, and action into one institutional view.</p><button onClick={() => navigate("/login")} className="mt-8 inline-flex items-center gap-2 rounded-lg bg-indigo-800 px-5 py-3.5 text-sm font-bold text-white hover:bg-indigo-700">Enter BodhSight <ArrowRight size={16} /></button></div></section>
      </main>
      <footer className="border-t border-border bg-background py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 sm:flex-row lg:px-8"><BrandLogo /><span className="text-xs text-secondary">Academic Intelligence Platform · {new Date().getFullYear()}</span></div></footer>
    </div>
  );
}
