import { useEffect, useState } from "react";
import { fetchReports } from "../api/agent10";
import type { ReportItem } from "../types/agent10";
import { FileText, Download, Plus } from "lucide-react";

export default function Reports() {
  const [reports, setReports] = useState<ReportItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  useEffect(() => {
    fetchReports().then(data => {
      setReports(data);
      setLoading(false);
    });
  }, []);

  const handleDownload = (id: string) => {
    setDownloadingId(id);
    setTimeout(() => {
      setDownloadingId(null);
      alert("Report downloaded successfully!");
    }, 1000);
  };

  if (loading) return <div className="p-6 text-gray-500">Loading reports...</div>;

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <FileText className="text-indigo-600" size={28} />
            Institutional Reports & Audit Logs
          </h1>
          <p className="text-sm text-gray-500 mt-1">
            Exportable documentation and executive summary reports generated by Agent 10.
          </p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium transition-colors shadow-sm">
          <Plus size={16} /> Generate New Report
        </button>
      </div>

      {/* Reports Table */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <table className="w-full text-left text-sm">
          <thead className="bg-gray-50 border-b border-gray-200 text-gray-500 font-medium">
            <tr>
              <th className="px-6 py-4">Report Title</th>
              <th className="px-6 py-4">Format</th>
              <th className="px-6 py-4">Category</th>
              <th className="px-6 py-4">Generated Date</th>
              <th className="px-6 py-4">File Size</th>
              <th className="px-6 py-4 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {reports.map((rep) => (
              <tr key={rep.id} className="hover:bg-gray-50 transition-colors">
                <td className="px-6 py-4 font-bold text-gray-900 flex items-center gap-2">
                  <FileText size={16} className="text-indigo-500 shrink-0" />
                  {rep.title}
                </td>
                <td className="px-6 py-4">
                  <span className="px-2 py-0.5 bg-gray-100 text-gray-700 rounded text-xs font-bold uppercase">
                    {rep.type}
                  </span>
                </td>
                <td className="px-6 py-4 text-gray-700">{rep.category}</td>
                <td className="px-6 py-4 text-gray-700">{rep.generated_date}</td>
                <td className="px-6 py-4 text-gray-500">{rep.size}</td>
                <td className="px-6 py-4 text-right">
                  <button 
                    onClick={() => handleDownload(rep.id)}
                    disabled={downloadingId === rep.id}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 rounded-md text-xs font-bold transition-colors"
                  >
                    {downloadingId === rep.id ? (
                      <>Downloading...</>
                    ) : (
                      <>
                        <Download size={14} /> Download
                      </>
                    )}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

    </div>
  );
}
