import { useState } from "react";
import { FileText, ShieldCheck, Printer, Lock } from "lucide-react";
import { getRolePermissions } from "../utils/rbac";
import type { ReportItem } from "../types/agent10";
import ExportMenu from "../components/ui/ExportMenu";
import { exportToExcel, exportToPDF, exportToWord } from "../utils/exportUtils";

export default function Reports() {
  const rawRole = localStorage.getItem("bodhsight_display_role") || localStorage.getItem("bodhsight_role") || "Dean";
  const permissions = getRolePermissions(rawRole);

  const [reports] = useState<ReportItem[]>([
    { id: "rep-01", title: "Principal & Management Executive Academic Summary", type: "PDF", generated_date: "2026-09-11", category: "Management", size: "2.4 MB" },
    { id: "rep-02", title: "Institutional Accreditation Compliance Audit", type: "PDF", generated_date: "2026-09-10", category: "Quality Assurance", size: "3.1 MB" },
    { id: "rep-03", title: "Agent 10 Exception & Statistical Deviation Log", type: "Excel", generated_date: "2026-09-10", category: "Exceptions", size: "840 KB" },
    { id: "rep-04", title: "Department-wise Course Priority & Intervention Plan", type: "Word", generated_date: "2026-09-09", category: "Interventions", size: "1.9 MB" }
  ]);

  const handleExportExcel = async (title: string) => {
    exportToExcel([{ "Report Title": title, "Date": new Date().toLocaleDateString(), "Status": "Generated" }], "Executive_Report");
  };

  const handleExportPDF = async (title: string) => {
    // In a real app this would capture a hidden rendering of the report or download a pre-generated file
    exportToPDF("reports-content", "Executive_Report", title);
  };

  const handleExportWord = async (title: string) => {
    exportToWord(title, [
      `Confidential Executive Report`,
      `Generated by BodhSight Analytics Engine.`,
      `Role: ${rawRole}`,
      `Date: ${new Date().toLocaleDateString()}`
    ], null, "Executive_Report");
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6" id="reports-content">
      <div className="bg-gradient-to-r from-surface via-indigo-950 to-violet-950 rounded-3xl p-8 text-primary shadow-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div className="space-y-2">
          <div className="inline-flex items-center gap-2 bg-surface/10 text-indigo-200 px-3 py-1 rounded-full text-xs font-bold border border-white/15">
            <FileText size={14} /> Executive Reporting Suite ({rawRole} View)
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight">Academic Performance Reports</h1>
          <p className="text-primary text-sm">
            {permissions.canExportOfficialReports 
              ? "Generate, export, and review consolidated institutional reports for management and accreditation bodies."
              : "Your current role is restricted from exporting institutional master reports."}
          </p>
        </div>
        <div className="bg-surface/10 backdrop-blur-md p-4 rounded-2xl border border-white/15 text-right">
          <div className="text-xs text-indigo-200 font-semibold uppercase">Compliance Status</div>
          <div className="text-xl font-black text-emerald-600 dark:text-emerald-400 mt-0.5 flex items-center gap-1.5 justify-end">
            <ShieldCheck size={18} /> 100% Verified
          </div>
        </div>
      </div>

      <div className="bg-surface rounded-3xl border border-border shadow-sm p-6 space-y-6">
        <div className="flex items-center justify-between border-b border-border pb-4">
          <h2 className="text-lg font-bold text-primary flex items-center gap-2">
            <Printer className="text-indigo-500" size={20} /> Available Institutional Exports
          </h2>
          <span className={`text-xs font-bold px-3 py-1 rounded-full ${permissions.canExportOfficialReports ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20" : "bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20"}`}>
            {permissions.canExportOfficialReports ? "Export Authorized" : "Restricted Access"}
          </span>
        </div>

        <div className="space-y-4">
          {reports.map((rep) => (
            <div key={rep.id} className="bg-surface-secondary rounded-2xl p-5 border border-border flex flex-col md:flex-row justify-between items-start md:items-center gap-4 hover:border-indigo-300 transition-all">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-0.5 bg-indigo-500/10 text-indigo-700 dark:text-indigo-400 text-xs font-extrabold rounded-md uppercase border border-indigo-500/20">
                    {rep.type}
                  </span>
                  <span className="text-xs font-bold text-secondary">{rep.category} • {rep.size}</span>
                </div>
                <h3 className="font-bold text-primary text-base">{rep.title}</h3>
                <p className="text-xs text-secondary">Generated with complete Agent 10 telemetry lineage.</p>
              </div>

              <div className="flex items-center gap-3">
                {permissions.canExportOfficialReports ? (
                  <ExportMenu 
                    onExportExcel={() => handleExportExcel(rep.title)}
                    onExportPDF={() => handleExportPDF(rep.title)}
                    onExportWord={() => handleExportWord(rep.title)}
                  />
                ) : (
                  <span className="inline-flex items-center gap-1 text-xs font-semibold text-secondary bg-surface px-4 py-2.5 rounded-xl border border-border">
                    <Lock size={14} /> Restricted Role
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
