import { useEffect, useState } from "react";
import { fetchReports } from "../api/agent10";
import type { ReportItem } from "../types/agent10";
import { FileText, Download, Plus, CheckCircle2 } from "lucide-react";

export default function Reports() {
  const [reports, setReports] = useState<ReportItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  useEffect(() => {
    fetchReports().then(data => {
      setReports(data);
      setLoading(false);
    });
  }, []);

  const handleDownload = (id: string) => {
    setDownloadingId(id);
    setTimeout(() => {
      setDownloadingId(null);
      alert("Report downloaded successfully!");
    }, 1000);
  };

  if (loading) return <div className="p-12 text-center text-indigo-600 font-medium">Loading reports...</div>;

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      
      {/* Header */}
      <div className="bg-gradient-to-r from-amber-900 via-indigo-900 to-violet-900 rounded-2xl p-6 text-white shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-amber-300 text-xs font-bold uppercase tracking-wider mb-1">
            <FileText size={14} /> Audit Documentation
          </div>
          <h1 className="text-2xl font-bold">Institutional Reports & Audit Logs</h1>
          <p className="text-amber-100 text-sm mt-0.5">Exportable documentation and executive summary reports generated by Agent 10.</p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2.5 bg-white text-indigo-950 hover:bg-amber-50 rounded-xl text-sm font-extrabold transition-all shadow-md">
          <Plus size={16} /> Generate New Report
        </button>
      </div>

      {/* Reports Table */}
      <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
        <table className="w-full text-left text-sm">
          <thead className="bg-slate-50 border-b border-gray-200 text-gray-600 font-bold uppercase text-xs tracking-wider">
            <tr>
              <th className="px-6 py-4">Report Title</th>
              <th className="px-6 py-4">Format</th>
              <th className="px-6 py-4">Category</th>
              <th className="px-6 py-4">Generated Date</th>
              <th className="px-6 py-4">File Size</th>
              <th className="px-6 py-4 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {reports.map((rep) => (
              <tr key={rep.id} className="hover:bg-slate-50 transition-colors">
                <td className="px-6 py-4 font-bold text-gray-900 flex items-center gap-2.5">
                  <div className="p-1.5 bg-indigo-50 text-indigo-600 rounded-lg">
                    <FileText size={16} />
                  </div>
                  {rep.title}
                </td>
                <td className="px-6 py-4">
                  <span className={`px-2.5 py-1 rounded-lg text-xs font-extrabold uppercase ${
                    rep.type === 'PDF' ? 'bg-rose-100 text-rose-700 border border-rose-200' :
                    rep.type === 'CSV' ? 'bg-emerald-100 text-emerald-700 border border-emerald-200' :
                    'bg-amber-100 text-amber-700 border border-amber-200'
                  }`}>
                    {rep.type}
                  </span>
                </td>
                <td className="px-6 py-4 text-gray-700 font-medium">{rep.category}</td>
                <td className="px-6 py-4 text-gray-700 font-medium">{rep.generated_date}</td>
                <td className="px-6 py-4 text-gray-500 font-semibold">{rep.size}</td>
                <td className="px-6 py-4 text-right">
                  <button 
                    onClick={() => handleDownload(rep.id)}
                    disabled={downloadingId === rep.id}
                    className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 rounded-xl text-xs font-bold transition-all shadow-sm border border-indigo-200"
                  >
                    {downloadingId === rep.id ? (
                      <>Downloading...</>
                    ) : (
                      <>
                        <Download size={14} /> Download
                      </>
                    )}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

    </div>
  );
}
